dataset: CIFAR100

# model
epochs: 60
pre_train_epochs: 20
trigger_train_epochs: 40
backdoor_start_epoch: 60
# epochs: 6
# pre_train_epochs: 1
# backdoor_start_epoch: 2
# trigger_train_epochs: 4
report_freq: 5
workers: 8
batch_size: 64
lr: 0.2
trigger_lr: 0.001
momentum: 0.9
weight_decay: 0.0005
grad_clip: 5.0
gamma: 0.97
decay_period: 1
resume: ''
start_epoch: 0
step_gamma: 0.1
stone1: 30
layers: 18
u_dim: 64
k: 2
parallel: false
load_model: 0
alpha: 0.05
eps: 0.75
corruption_amp: 5.0
backdoor_start: true
poison_budget: 0.5
optimal_sel: true
saliency_map_injection: true
window_size: 5
